### ISSUE TITLE
missing xml files

### ISSUE THREAD

**Issue by verybigelephants** [jmonta01/somafm-webplayer#11]
why are the xml files not in the dist directory?
i have found the xml files in app/data but the list is not complete

i am confused, i think i may have misunderstood this player

**Comment by jmonta01** [comment]
The xml files packaged with the player are only for local development and are only a tiny subset. The only way to test locally is to use these packaged xml files, due to cors. The actual xml & pls files are generated from the streaming servers of somafm. So the dist build ignores the dev xml files and targets the actual streaming server data of somafm.

Let me know if that does not clear it up.

Thanks,
Jason

**Comment by verybigelephants** [comment]
ok thanks, now i understand
